on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Cache pnpm dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('backend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: pnpm install
        working-directory: ./backend
        env:
          PNPM_STORE_PATH: ~/.pnpm-store

      - run: pnpm run test --run
        working-directory: ./backend
        env:
          PNPM_STORE_PATH: ~/.pnpm-store
